name: MafkeesPlugin
version: 1.0
main: me.mafkees92.Main
author: mafkees92
description: MafkeesPlugin
commands:
   rename:
      description: Rename an item in your hand
      usage: /<command>
   givecustompotion:
      description: Give a player a custom potion
      usage: /<command>
      aliases: [gcp, givecustom]
   givevoucher:
      description: Give a player a custom voucher
      usage: /<command>
   flytime:
      description: Get the remaining flytime
      usage: /<command>
softdepends: [MVdWPlaceholderAPI, PlaceholderAPI]