name: MafkeesPlugin
version: 1.0
main: me.mafkees92.Main
author: mafkees92
description: MafkeesPlugin
commands:
   rename:
      description: Rename an item in your hand
      usage: /<command>
   setlore:
      description: Set the lore of the item in your hand
      usage: /<command>
   givecustompotion:
      description: Give a player a custom potion
      usage: /<command>
      aliases: [gcp, givecustom]
   givevoucher:
      description: Give a player a custom voucher
      usage: /<command>
   flytime:
      description: Get the remaining flytime
      usage: /<command>
   givecustomhopper:
      description: Add Hopper test
      usage: /<command>
   startparkour:
      description: Start the parkour at spawn
      usage: /<command>
   islandchest:
      description: Open island chest
      usage: /<command>
   islandinvsee:
      description: invsee island chests
      usage: /<command>
   upgradeislandchestsize:
      description: upgrade the size of islands chests (console only)
      usage: /<command>
   givechunkloader:
      description: give a chunkloader to a player
      usage: /<command>
   givevoidchest:
      description: give a voidchest to a player
      usage: /<command>
   gamble:
      description: open the gambler inventory
      usage: /<command>
   help:
      description: override help command
      usage: /<command>
   parkour:
      description: show parkour information
      usage: /<command>
   hub:
      description: go to the hub/spawn
      usage: /<command>
   rules:
      description: Display the server rules
      usage: /<command>
      
softdepends: [MVdWPlaceholderAPI, PlaceholderAPI, Vault]
depend: [Multiverse-Core, ProtocolLib, HolographicDisplays, HeadDatabase]